-- ============================================================
-- SQL Pendiente — Intranet AE
-- Última revisión: 2026-07-08 (verificado contra BD real vía REST API)
--
-- REGLA: solo están aquí cosas que NO se han podido verificar
-- vía REST API. Una vez ejecutadas, mover al historial abajo.
-- ============================================================


-- ════════════════════════════════════════════════════════════
-- PENDIENTE — ejecutar en Supabase → SQL Editor
-- ════════════════════════════════════════════════════════════

-- ── migration_ras_documentos_familia.sql ───────────────────────────────────
-- Estado: LISTO PARA EJECUTAR — verificado por REST 2026-07-22 que NO existe aún
-- (ras.documentos_familia → PGRST205; no hay bucket ras-documentos-privados).
-- Script: docs/sql/migration_ras_documentos_familia.sql
-- Crea ras.documentos_familia (cesión de derechos de imagen y otros documentos
-- legales por familia, 1→N, soporta varios titulares) + bucket PRIVADO
-- ras-documentos-privados + RLS solo-autenticados (NO anon).
-- Lo consume el módulo de conservación: sección "Cesión de derechos de imagen"
-- en /intranet/ras/conservacion/[id] y el API /api/ras/conservacion/[id]/documentos.
-- Sin esto: esa sección responde vacío / la subida da error (tabla y bucket
-- inexistentes); el resto del módulo funciona igual.
-- Verificar tras correr: select to_regclass('ras.documentos_familia');


-- ════════════════════════════════════════════════════════════
-- HISTORIAL — ya ejecutado en producción
-- ════════════════════════════════════════════════════════════

-- ── 2026-03  Schemas siembra + ras + tablas base ─────────────────────────────
-- ── 2026-03  GRANTs siembra + ras ────────────────────────────────────────────
-- ── 2026-04  siembra.familias ampliada (datos CSV) ───────────────────────────
-- ── 2026-04  ras.familias ampliada (socioeconómicos) ─────────────────────────
-- ── 2026-04  ras.familias columnas conservación ──────────────────────────────
-- ── 2026-04  siembra.fotos_predio + ras.fotos_predio creadas ─────────────────
-- ── 2026-04  public.consentimientos + RLS ────────────────────────────────────
-- ── 2026-04  public.user_profiles.can_access_intranet ────────────────────────
-- ── 2026-04  public.vehicle_inspections.kilometraje ──────────────────────────
-- ── 2026-05  siembra.predios + siembra.evaluaciones_campo ────────────────────
-- ── 2026-05  migration_campo_multizona.sql (PWA offline + anon RLS) ──────────
-- ── 2026-05  ras.monitoreos ──────────────────────────────────────────────────
-- ── 2026-05  migration_schemas_people_fleet.sql ───────────────────────────────
--             (schemas people + fleet creados, tablas movidas, triggers auth.users)
-- ── 2026-05  migration_ejecutivo.sql (schema ejecutivo, sesiones, indicaciones)
-- ── 2026-05  migration_ejecutivo_v2.sql (columna nota + estado rechazado)
-- ── 2026-05  fleet.vehicle_documents creada (4 filas — una por vehículo)
-- ── 2026-05  migration_modulo_juridico.sql (schema juridica + 3 tablas + bucket)
--             Confirmado en BD: schema juridica vivo, bucket juridica-documentos (privado),
--             usuario legal@amazoniaemprende.com (department=Juridica). Los datos eran de prueba.
-- ── 2026-05  migration_soft_delete_familias.sql (siembra.familias.deleted_at) ─
-- ── 2026-06-18  cleanup_legacy.sql (juridica.aliados_legacy eliminada tras cutover a core) ─
-- ── 2026-06-19  migration_core.sql ───────────────────────────────────────────
--             Schema 'core' (aliados · predios · predio_propietarios · expedientes) +
--             cutover de jurídica sobre core. Verificado por REST: core.aliados (2 filas),
--             core.predios, juridica.debida_diligencia (2 filas). Ver docs/CORE_MIGRACION.md.
-- ── 2026-06-19/20  migration_geo.sql + v2 + v3 ────────────────────────────────
--             Schema 'geo', tabla geo.zonas + PostGIS. v2 agrega columnas
--             propiedades (jsonb) / perimetro_m y función geo.zonas_de_predio().
--             v3 agrega geo.crear_zona_union() (unir zonas superpuestas).
--             Verificado por REST: geo.zonas (3 filas, con propiedades y perimetro_m
--             poblados); crear_zona_union responde error de negocio (no "function not
--             found"), confirmando que existe — usada en app/api/sig/ingesta/route.ts.
-- ── 2026-06-20  migration_core_matriculas.sql (core.predios.matriculas text[]) ─
--             Verificado por REST: columna matriculas poblada desde matricula_inmobiliaria.
-- ── 2026-06-30  migration_catalogo.sql + seed_catalogo_especies.sql ──────────
--             Schema 'catalogo', tabla catalogo.especies — maestro único de especies
--             (botánica + RAS + vivero). Verificado por REST: 148 filas.
-- ── 2026-07-01  migration_ras_arboles.sql + seed_ras_arboles.sql ─────────────
--             ras.arboles_semilleros (normalizada, FK especie_id → catalogo.especies)
--             + vistas ras.v_indicadores_predio y ras.v_arboles_con_especie.
--             Verificado por REST: 523 filas (coincide con "523 árboles listos para subir").
-- ── 2026-07-28  seed_juridica_aliados.sql (85 aliados + 100 predios del Excel de jurídica) ─
--             Verificado por REST: core.aliados 89, core.predios 104. Etapa 'juridica', DD 'borrador'.
-- ── 2026-07-28  migration_zona_revision.sql (SIG II: geo.zona_revision + RPC geo.revisar_zona) ─
--             Verificado por REST: la tabla existe y el RPC responde a anon (P0001 en acción
--             inválida, sin escribir). Las correcciones de zonas hechas en campo ya sincronizan.
-- (Ver SQL completo en SUPABASE_SCHEMAS.md)
