-- ============================================================
-- SQL Pendiente — Intranet AE
-- Última revisión: 2026-09-20 (verificado contra BD real vía REST API)
--
-- REGLA: solo están aquí cosas que NO se han podido verificar
-- vía REST API. Una vez ejecutadas, mover al historial abajo.
-- ============================================================


-- ════════════════════════════════════════════════════════════
-- PENDIENTE — ejecutar en Supabase → SQL Editor
-- ════════════════════════════════════════════════════════════

-- ── 2026-09-19  migration_predio_grupos_v2.sql — endurecer los RPC ──────────
-- Dos REVOKE. Postgres concede EXECUTE a PUBLIC en cada función nueva, así que
-- con la key anon los RPC core.fusionar_predios y core.disolver_grupo SE
-- EJECUTAN (verificado por REST: responden P0001, el RAISE de la función).
-- NO es un hueco abierto: la función no es SECURITY DEFINER, por dentro corre
-- como anon y la RLS de core.predios le devuelve 0 filas → la validación aborta
-- siempre; y anon no tiene INSERT/UPDATE en las tablas (42501). Se cierra
-- porque es la barrera que no depende de que nadie se equivoque después.
-- Lo único expuesto mientras tanto: el mensaje de error dice si un uuid de
-- predio existe. Sin prisa.

-- ── 2026-09-01  merge_aliados_duplicados.sql — BLOQUE 2, opcional ───────────
-- El BLOQUE 1 (fusión de "Álvaro Marlés Artunduaga" + "… 2") YA SE CORRIÓ:
-- verificado por REST el 2026-09-01 — quedan 94 aliados (eran 95), los dos
-- predios San Francisco Lote 1 y 2 cuelgan del aliado conservado.
-- Queda pendiente solo el BLOQUE 2 (borrar la ficha sin predio de Rodrigo Silva
-- Hermida), comentado a propósito: es una decisión del usuario.
-- El BLOQUE 3 son consultas de lectura, se pueden correr cuando sea.

-- Antes del 2026-09-17 no quedaba ninguna migración de esquema pendiente
-- (verificado por REST el 2026-08-12).


-- ════════════════════════════════════════════════════════════
-- HISTORIAL — ya ejecutado en producción
-- ════════════════════════════════════════════════════════════


-- ── 2026-09-20  migration_nucleacion_v2.sql ─────────────────────────────────
--             Un lote sale de lo que campo verificó. confirmar_lotes solo toma
--             zonas en 'validada' (una 'potencial' es una propuesta de la
--             oficina que nadie fue a mirar) y guarda el estado anterior en
--             propiedades; deshacer_lotes lo restituye en vez de dejar todo en
--             'validada', que le atribuía una verificación inexistente.
--             Verificado por REST el 2026-09-20 sobre «Los Andes» (predio sin
--             trabajo de campo, restaurado al terminar): potencial → devuelve 0
--             y no toca la zona · validada → definitiva guardando quién, cuándo
--             y de dónde venía · deshacer vuelve a validada y limpia SOLO sus
--             tres claves (los atributos del .dbf quedan intactos) · la key anon
--             sigue sin poder ejecutar ninguno de los dos (42501).

-- ── 2026-09-20  migration_nucleacion.sql ────────────────────────────────────
--             Lotes de siembra (geo.zonas.estado='definitiva') + geo.nucleos y
--             geo.nucleos_carga + crear_nucleo/abrir_carga_nucleos/
--             cerrar_carga_nucleos + lotes_de_predio/nucleos_de_predio.
--             Verificado por REST el 2026-09-20, prueba de humo completa sobre
--             «Los Andes» (creada y borrada, base como estaba): la ASIGNACIÓN
--             ESPACIAL funciona — el núcleo dentro del lote se engancha solo y
--             el que cae fuera queda con zona_id NULL y se cuenta aparte · el
--             candado que impide deshacer un lote con nucleación responde · la
--             key anon no lee las tablas ni ejecuta los RPC (42501).

-- ── 2026-09-20  migration_renombrar_carga.sql + _fix.sql ────────────────────
--             «Lote» dejaba de significar dos cosas: la subida versionada del
--             SIG pasó a llamarse CARGA (geo.zonas_carga, abrir_carga,
--             cerrar_carga, zonas.carga_id, reemplazada_por_carga,
--             conflicto_con_carga, crear_zona(p_carga_id)).
--             ⚠ El primer archivo MURIÓ A MITAD con 42P13 (faltaba el DROP de
--             zonas_historial, cuya columna de SALIDA cambia de nombre) y el
--             BEGIN/COMMIT NO protegió: el editor SQL de Supabase ejecuta las
--             sentencias por separado. El _fix.sql terminó la otra mitad.
--             LECCIÓN, para las próximas: escribir cada sentencia de modo que
--             pueda correrse sola y de nuevo, sin contar con la transacción.
--             Verificado por REST el 2026-09-20: zonas_carga existe, zonas_lote
--             no, zonas_historial responde, v_zonas_conflicto trae
--             conflicto_con_carga, y abrir_lote/cerrar_lote ya no están.

-- ── 2026-09-17  migration_predio_grupos.sql ─────────────────────────────────
--             Unidades de siembra: varios predios que comparten UN polígono.
--             core.predio_grupos + core.predio_grupo_miembros (con índice único
--             PARCIAL sobre predio_id WHERE activo) + core.v_predio_grupos + los
--             RPC core.fusionar_predios / core.disolver_grupo + la columna
--             geo.zonas.grupo_id.
--             Verificado por REST el 2026-09-19, prueba de humo completa con dos
--             predios reales sin cartografía (creada y borrada, la base quedó
--             como estaba — 0 grupos, 0 miembros, 0 zonas con grupo_id):
--             fusionar OK · la vista devuelve n_predios/n_municipios/
--             n_propietarios/principal bien · rechaza fusionar un predio que ya
--             está en una unidad vigente · rechaza un principal que no está en
--             la selección · disolver deja la unidad fuera de la vista y
--             conserva los miembros con activo=false · disolver dos veces
--             devuelve false sin error · y tras disolver se puede volver a
--             fusionar (el índice parcial funciona).
--             La key anon no puede leer ni escribir las tablas nuevas (42501),
--             pero SÍ ejecuta los RPC → ver migration_predio_grupos_v2.sql arriba.

-- ── 2026-09-17  migration_normalizar_ubicaciones.sql ─────────────────────────
--             21 UPDATE de texto sobre core.predios: una sola escritura por
--             municipio, vereda y zona AE, para que el mismo lugar no apareciera
--             dos veces en los filtros del tablero SIG.
--             Verificado por REST el 2026-09-19: municipio 6 → **4** valores
--             (Florencia 35 · Morelia 72 · Por definir 3 · Solano 1),
--             zona_ae 5 → **4**, vereda 47 → **42**; CERO pares que solo se
--             diferencien en mayúsculas o tildes en los tres campos; los 111
--             predios de entonces siguen ahí y ninguno quedó con municipio vacío
--             ni vereda en blanco (hoy son 110: el 2026-09-20 se borró un predio
--             de prueba, el único que había en Solano). Volver a pasar la función canónica sobre la base no
--             cambia nada (es idempotente).
--             Se mantiene limpio porque las rutas que escriben core.predios
--             normalizan en el SERVIDOR (lib/veredas-caqueta.ts).

-- ── 2026-09-14  migration_orden_hojas_juridica.sql ───────────────────────────
--             Jurídica invierte el orden: HOJA 2 = análisis jurídico, HOJA 3 =
--             antecedentes. Estado nuevo 'analisis_ok' en el CHECK de
--             juridica.debida_diligencia.estado, y el estado pasa a derivarse de
--             las dos hojas. Verificado por REST el 2026-09-14: el comentario de
--             la columna que escribe el BLOQUE 1 (justo después del CHECK) está
--             puesto; reparto borrador 81 · antecedentes_ok 5 · juridico_ok 3 ·
--             aprobado 19 · rechazado 3 (el esperado tras el BLOQUE 3); y la regla
--             de lib/juridica-schema.ts corrida contra los 111 predios da 0
--             desfases. El CHECK no se pudo leer por REST: se infiere del
--             comentario, no de escribir un 'analisis_ok' de prueba.

-- ── 2026-09-08  migration_proyecto_fuente.sql ────────────────────────────────
--             Clasificación del predio por proyecto y por fuente de información:
--             catalogo.proyectos (2 filas: conexion_biodiversa, ley_arbol),
--             catalogo.fuentes_informacion (3: socializacion_veredal,
--             socializacion_comunitaria, lacteos_del_hogar) y las columnas
--             core.predios.tipo_proyecto + .fuente_informacion (FK por código).
--             Verificado por REST el 2026-09-08: los 5 registros de catálogo con
--             su orden, las dos columnas presentes, lectura anon OK (es la que
--             usa el navegador) y los 111 predios existentes en NULL — se
--             clasifican desde la intranet con el filtro «Sin proyecto asignado».

-- ── 2026-03  Schemas siembra + ras + tablas base ─────────────────────────────
-- ── 2026-03  GRANTs siembra + ras ────────────────────────────────────────────
-- ── 2026-04  siembra.familias ampliada (datos CSV) ───────────────────────────
-- ── 2026-04  ras.familias ampliada (socioeconómicos) ─────────────────────────
-- ── 2026-04  ras.familias columnas conservación ──────────────────────────────
-- ── 2026-04  siembra.fotos_predio + ras.fotos_predio creadas ─────────────────
-- ── 2026-04  public.consentimientos + RLS ────────────────────────────────────
-- ── 2026-04  public.user_profiles.can_access_intranet ────────────────────────
-- ── 2026-04  public.vehicle_inspections.kilometraje ──────────────────────────
-- ── 2026-05  siembra.predios + siembra.evaluaciones_campo ────────────────────
-- ── 2026-05  migration_campo_multizona.sql (PWA offline + anon RLS) ──────────
-- ── 2026-05  ras.monitoreos ──────────────────────────────────────────────────
-- ── 2026-05  migration_schemas_people_fleet.sql ───────────────────────────────
--             (schemas people + fleet creados, tablas movidas, triggers auth.users)
-- ── 2026-05  migration_ejecutivo.sql (schema ejecutivo, sesiones, indicaciones)
-- ── 2026-05  migration_ejecutivo_v2.sql (columna nota + estado rechazado)
-- ── 2026-05  fleet.vehicle_documents creada (4 filas — una por vehículo)
-- ── 2026-05  migration_modulo_juridico.sql (schema juridica + 3 tablas + bucket)
--             Confirmado en BD: schema juridica vivo, bucket juridica-documentos (privado),
--             usuario legal@amazoniaemprende.com (department=Juridica). Los datos eran de prueba.
-- ── 2026-05  migration_soft_delete_familias.sql (siembra.familias.deleted_at) ─
-- ── 2026-06-18  cleanup_legacy.sql (juridica.aliados_legacy eliminada tras cutover a core) ─
-- ── 2026-06-19  migration_core.sql ───────────────────────────────────────────
--             Schema 'core' (aliados · predios · predio_propietarios · expedientes) +
--             cutover de jurídica sobre core. Verificado por REST: core.aliados (2 filas),
--             core.predios, juridica.debida_diligencia (2 filas). Ver docs/CORE_MIGRACION.md.
-- ── 2026-06-19/20  migration_geo.sql + v2 + v3 ────────────────────────────────
--             Schema 'geo', tabla geo.zonas + PostGIS. v2 agrega columnas
--             propiedades (jsonb) / perimetro_m y función geo.zonas_de_predio().
--             v3 agrega geo.crear_zona_union() (unir zonas superpuestas).
--             Verificado por REST: geo.zonas (3 filas, con propiedades y perimetro_m
--             poblados); crear_zona_union responde error de negocio (no "function not
--             found"), confirmando que existe — usada en app/api/sig/ingesta/route.ts.
-- ── 2026-06-20  migration_core_matriculas.sql (core.predios.matriculas text[]) ─
--             Verificado por REST: columna matriculas poblada desde matricula_inmobiliaria.
-- ── 2026-06-30  migration_catalogo.sql + seed_catalogo_especies.sql ──────────
--             Schema 'catalogo', tabla catalogo.especies — maestro único de especies
--             (botánica + RAS + vivero). Verificado por REST: 148 filas.
-- ── 2026-07-01  migration_ras_arboles.sql + seed_ras_arboles.sql ─────────────
--             ras.arboles_semilleros (normalizada, FK especie_id → catalogo.especies)
--             + vistas ras.v_indicadores_predio y ras.v_arboles_con_especie.
--             Verificado por REST: 523 filas (coincide con "523 árboles listos para subir").
-- ── 2026-07-28  seed_juridica_aliados.sql (85 aliados + 100 predios del Excel de jurídica) ─
--             Verificado por REST: core.aliados 89, core.predios 104. Etapa 'juridica', DD 'borrador'.
-- ── 2026-07-28  migration_zona_revision.sql (SIG II: geo.zona_revision + RPC geo.revisar_zona) ─
--             Verificado por REST: la tabla existe y el RPC responde a anon (P0001 en acción
--             inválida, sin escribir). Las correcciones de zonas hechas en campo ya sincronizan.
-- ── ~2026-08   migration_ras_documentos_familia.sql ──────────────────────────
--             Verificado por REST 2026-08-12: ras.documentos_familia existe con 9 filas.
--             (Estuvo listado como pendiente desde 2026-07-22; se corrió en algún momento
--             entre esa fecha y hoy.)
-- ── 2026-08-11  migration_geo_versionado.sql ─────────────────────────────────
--             Versionado de zonas del SIG y tolerancia de la app de campo.
--             Verificado por REST 2026-08-12: geo.zonas_lote y geo.v_zonas_conflicto existen;
--             geo.revisar_zona quedó con la firma de 10 argumentos SIN sobrecarga duplicada
--             (una llamada con los 9 viejos resuelve limpio); las 25 zonas existentes siguen
--             vigentes — la migración no retiró ninguna.
--             Qué cambió: cada subida del SIG es un LOTE con versión (geo.zonas_lote =
--             backup 1, 2, 3...) y lo reemplazado queda vigente=false, consultable, NO borrado.
--             Antes, modo 'sobreescribir' hacía DELETE de geo.zonas y crear_zona_union también,
--             así que los zona_id que el celular había descargado dejaban de existir y
--             geo.revisar_zona levantaba excepción: el trabajo de terreno quedaba atascado sin
--             poder aplicarse nunca. Ahora el RPC revive la zona retirada o la recrea con la
--             geometría de respaldo que manda el celular, y cerrar_lote no retira zonas que
--             campo ya trabajó (las marca en geo.v_zonas_conflicto para resolver en la oficina).
-- (Ver SQL completo en SUPABASE_SCHEMAS.md)
